<?php

namespace Database\Seeders;

use App\Models\GasolineStation;
use App\Services\ActivityLogsService;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class GasolineStationSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(ActivityLogsService $service)
    {
        $gasoline_stations = array(

            //BAAO

            //7.0810192004704895, 125.58281519182457
            [
                'id' => 1,
                'name' => 'RPJR ENTERPRISE',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Maharlika Highway, Nabua 4432',
                'latitude' => '13.456220',
                'longitude' => '123.363780',
                'municipality_id' => '1',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 2,
                'name' => 'GAITE SERVICE STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Maharlika Highway, Nabua 4432',
                'latitude' => '13.463533',
                'longitude' => '123.363939 ',
                'municipality_id' => '1',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 3,
                'name' => 'LAHAHA GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Maharlika Highway, San Isidro Nabua 4432',
                'latitude' => '13.468241',
                'longitude' => '123.359198',
                'municipality_id' => '1',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 4,
                'name' => 'FLYING V ',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Baao-Iriga Road 4432',
                'latitude' => '13.456767',
                'longitude' => '123.364776',
                'municipality_id' => '1',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 5,
                'name' => 'TURBOLANE GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'San Isidro Baao 4431',
                'latitude' => '13.441147',
                'longitude' => '123.404850',
                'municipality_id' => '1',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
           
            //BALATAN
            [
                'id' => 6,
                'name' => 'JDRS GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Kabungan, Balatan Camarines Sur',
                'latitude' => '13.362419',
                'longitude' => '123.268142',
                'municipality_id' => '2',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 7,
                'name' => 'GIBN GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Zone 6, Sirama, Balatan ',
                'latitude' => '13.316514',
                'longitude' => '123.237630',
                'municipality_id' => '2',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 8,
                'name' => 'OH MY GAZ ',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Zone 2, Duran Balatan',
                'latitude' => '13.313051',
                'longitude' => '123.237112',
                'municipality_id' => '2',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 9,
                'name' => 'GBN GAS STATION AND BALATAN HARDWARE INC.',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Masbate Street, Balatan, 4436',
                'latitude' => '13.315331',
                'longitude' => '123.234038',
                'municipality_id' => '2',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],

            //BUHI

            [
                'id' => 10,
                'name' => 'SHELL BUHI GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Buhi-Iriga Road, 4433',
                'latitude' => '13.426977',
                'longitude' => '123.518380',
                'municipality_id' => '4',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 11,
                'name' => 'VGAS GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Sagrada, Buhi-Iriga Road',
                'latitude' => '13.414616',
                'longitude' => '123.512746',
                'municipality_id' => '4',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 12,
                'name' => 'LETTYS GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Santa Justina, Buhi–Iriga Road, Zone 5',
                'latitude' => '13.400538',
                'longitude' => '123.488312',
                'municipality_id' => '4',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],

            // BULA

            [
                'id' => 13,
                'name' => 'RINCONADA PRIME FUELS',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Nabua-Balatan Road, 4434',
                'latitude' => '13.419480',
                'longitude' => '123.298369',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 14,
                'name' => 'MGY FUELS',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Panoypoyan Zone 3',
                'latitude' => '13.454059',
                'longitude' => '123.257923',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 15,
                'name' => 'SC DECENA FUEL STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Pili-Bula Road',
                'latitude' => '13.471410',
                'longitude' => '123.277879',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 16,
                'name' => 'CARIAGA PETROLEUM',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Bagumabayan',
                'latitude' => '13.479757',
                'longitude' => '123.278946',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 17,
                'name' => 'MGY GAZ STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Bagumabayan',
                'latitude' => '13.481824',
                'longitude' => '123.279433',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 18,
                'name' => 'VMRM GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Santo Domingo',
                'latitude' => '13.516977',
                'longitude' => '123.283623',
                'municipality_id' => '5',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],

            //IRIGA
            [
                'id' => 19,
                'name' => 'AMBYGAZ FUEL STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Iriga-Buhi Road',
                'latitude' => '13.412776',
                'longitude' => '123.449740',
                'municipality_id' => '6',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 20,
                'name' => 'PETRO GAZZ',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Guevara Street, San Juan, Iriga City',
                'latitude' => '13.420013',
                'longitude' => '123.421016',
                'municipality_id' => '6',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
           
            [
                'id' => 21,
                'name' => 'JOG GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Santol street, Santa Teresita, Iriga City',
                'latitude' => '13.486706',
                'longitude' => '123.432909',
                'municipality_id' => '6',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 22,
                'name' => 'DIMAIWAT FUEL STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Zone 3, Perpetual Help, Iriga City 4431',
                'latitude' => '13.468384',
                'longitude' => '123.414168',
                'municipality_id' => '6',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],

            //NABUA
            [
                'id' => 23,
                'name' => 'J. PEYRA GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Maharlika Highway, Nabua 4434',
                'latitude' => '13.419426',
                'longitude' => '123.368071',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 24,
                'name' => 'CONSTANT FUEL',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Nabua-Balatan Road,4434',
                'latitude' => '13.405662',
                'longitude' => '123.370182',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 25,
                'name' => '1FB FUEL STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Magringao St.San Antonio Ogbon,4434',
                'latitude' => '13.398985',
                'longitude' => '123.347809',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 26,
                'name' => 'MANG INGO GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Road Side, Santo Domingo, Nabua 4434',
                'latitude' => '13.404355',
                'longitude' => '123.335392',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 27,
                'name' => 'A PLUS GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Road Side, Santo Domingo, Nabua 4434',
                'latitude' => '13.404355',
                'longitude' => '123.327651',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 28,
                'name' => 'LUCKY ROADSIDE GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Santo Domingo,  Nabua 4434',
                'latitude' => '13.405891',
                'longitude' => '123.327651',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 29,
                'name' => 'BLUE PRIME GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Zone 6, Panganiban Angustia, Inapatan',
                'latitude' => '13.374726',
                'longitude' => '123.273102',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 30,
                'name' => 'RINCONADA PRIME FUELS',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Inapatan',
                'latitude' => '13.395121',
                'longitude' => '123.303211',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 31,
                'name' => 'ULTRA FUELS',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Inapatan, Dolorosa ',
                'latitude' => '13.399604',
                'longitude' => '123.312511',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
            [
                'id' => 32,
                'name' => 'ROLLBACK GAS STATION',
                'contact' => '09659312005',
                'email' => 'gasolinestation@email.com',
                'address' => 'Nabua-Balatan Road, 4434',
                'latitude' => '13.401502',
                'longitude' => '123.316394',
                'municipality_id' => '7',
                'time_started_at' => now()->setTime(6,0,0,0),
                'time_ended_at' => now()->setTime(18,0,0,0),
                'is_always_open' => false,
                'created_at' => now(),
            ],
          
        );

        GasolineStation::insert($gasoline_stations);

        GasolineStation::all()->each(function($gasoline_station) use($service){
            $gasoline_station
            ->addMedia(public_path("/img/tmp_files/gasoline_stations/1.png"))
            ->preservingOriginal()
            ->toMediaCollection('featured_photo'); // assign gasoline featured photo | by default it is the 1.png

            $service->log_activity(model:$gasoline_station, event:'added', model_name: 'Gasoline Station', model_property_name: $gasoline_station->name);
        });
    }
}